#!/usr/bin/bash

if [ $# -eq 0 ]; then
    echo error: missing arguments
    exit 1
fi

mainarg=$(echo "$@" | awk '{print $NF}')
finalstr=
is_enable_zl=false

while getopts ":t:z:" opt; do
    case "${opt}" in
        t)
            encstr=$(xxd -u -ps <(echo -n "$mainarg"))
            prefixchar=
            sufixchar=
            case "$OPTARG" in
                url)
                    prefixchar="%"
                    ;;
                2url)
                    prefixchar="%25"
                    ;;
                html-dec) #TODO
                    prefixchar="&#"
                    sufixchar=";"
                    is_enable_zl=true
                    # TODO
                    ;;
                html-hex)
                    prefixchar="&#x"
                    sufixchar=";"
                    is_enable_zl=true
                    ;;
                unicode)
                    prefixchar="\u00"
                    ;;
                unicode-es6)
                    prefixchar="\u{"
                    sufixchar="}"
                    is_enable_zl=true
                    ;;
                *)
                    echo error: invalid argument
                    exit 4
                ;;
            esac
            
            for (( i=0; i<${#encstr}; i+=2 )); do
                finalstr+=$(echo "$prefixchar${encstr:$i:2}$sufixchar")
            done
            ;;
        z)
            zeros=""
            if $is_html_enc; then
                for ((i=0; i<"$OPTARG"; i++)); do
                    zeros="$zeros"0
                done
                finalstr=$(echo $finalstr | sed -E "s/(&#x|&#|\\u\{)/\1$zeros/g")
            fi
            ;;
        :)
            echo error: missing required argument in option
            exit 2
            ;;
        ?)
            echo error: non-existent option
            exit 3
            ;;
    esac
done

echo "$finalstr"

exit 0
