#!/usr/bin/bash

if [ $# -eq 0 ]; then
    echo error: missing arguments
    exit 1
fi

mainarg=$(echo "$@" | awk '{print $NF}')
finalstr=
is_enable_zl=false
enc_type="hex"

while getopts ":t:z:" opt; do
    case "${opt}" in
        t)
            encstr=$(xxd -u -ps <(echo -n "$mainarg"))
            prefixchar=
            sufixchar=
            char=
            is_sql_char=false
            case "$OPTARG" in
                url)
                    prefixchar="%"
                    ;;
                2url)
                    prefixchar="%25"
                    ;;
                html-dec)
                    prefixchar="&#"
                    sufixchar=";"
                    is_enable_zl=true
                    enc_type="dec"
                    ;;
                html-hex)
                    prefixchar="&#x"
                    sufixchar=";"
                    is_enable_zl=true
                    ;;
                unicode)
                    prefixchar="\u00"
                    ;;
                unicode-es6)
                    prefixchar="\u{"
                    sufixchar="}"
                    is_enable_zl=true
                    ;;
                hex)
                    prefixchar="\x"
                    ;;
                sql)
                    prefixchar="0x"
                    ;;
                octal)
                    prefixchar="\\"
                    enc_type="octal"
                    ;;
                css)
                    prefixchar="\00"
                    ;;
                html-entity) #TODO
                    ;;
                sql-char-hex)
                    prefixchar="CHAR(0x"
                    sufixchar=")"
                    is_sql_char=true
                    ;;
                sql-char-dec)
                    prefixchar="CHAR("
                    sufixchar=")"
                    enc_type="dec"
                    is_sql_char=true
                    ;;
                *)
                    echo error: invalid argument
                    exit 4
                ;;
            esac
            
            for (( i=0; i<${#encstr}; i+=2 )); do
                char="${encstr:$i:2}"
                if [ "$enc_type" != "hex" ]; then
                    case "$enc_type" in
                        octal)
                            char=$(printf "%o" $((16#"$char")))
                            ;;
                        dec)
                            char=$(printf "%d" $((16#"$char")))
                            ;;
                    esac
                fi
                finalstr+=$(echo "$prefixchar$char$sufixchar")
                
                if "$is_sql_char" && [ "$i" -lt $((${#encstr} - 2)) ]; then
                    finalstr+="+"
                fi
            done
            ;;
        z)
            zeros=""
            if $is_html_enc; then
                for ((i=0; i<"$OPTARG"; i++)); do
                    zeros="$zeros"0
                done
                finalstr=$(echo $finalstr | sed -E "s/(&#x|&#|\\u\{)/\1$zeros/g")
            fi
            ;;
        :)
            echo error: missing required argument in option
            exit 2
            ;;
        ?)
            echo error: non-existent option
            exit 3
            ;;
    esac
done

echo "$finalstr"

exit 0
